version: '3.2'
services :
  db:
    image: postgres:latest
    ports:
      - "5400:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8080"